set foreign_key_checks = 0;

delete from sys_usergroup_member where usergroup_objid like 'rpt%encoding_%';
delete from sys_usergroup where role like 'encoding_%';

set foreign_key_checks = 1;


/* INITIAL LAND SPECIFIC CLASSES */
delete from landspecificclass;
INSERT INTO `landspecificclass` (`objid`, `state`, `code`, `name`) VALUES ('COMMERCIAL', 'APPROVED', 'C', 'COMMERCIAL');
INSERT INTO `landspecificclass` (`objid`, `state`, `code`, `name`) VALUES ('INDUSTRIAL', 'APPROVED', 'I', 'INDUSTRIAL');
INSERT INTO `landspecificclass` (`objid`, `state`, `code`, `name`) VALUES ('MINERAL', 'APPROVED', 'M', 'MINERAL');
INSERT INTO `landspecificclass` (`objid`, `state`, `code`, `name`) VALUES ('RESIDENTIAL', 'APPROVED', 'R', 'RESIDENTIAL');
INSERT INTO `landspecificclass` (`objid`, `state`, `code`, `name`) VALUES ('TIMBERLAND', 'APPROVED', 'T', 'TIMBERLAND');


/* RPT PARAMETER */
DELETE FROM rptparameter;
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('AREA_SQM', 'APPROVED', 'AREA_SQM', 'AREA IN SQM', 'AREA IN SQUARE METER', 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('DISTANCE_TO_AWR', 'APPROVED', 'DISTANCE_TO_AWR', 'DISTANCE TO AWR', '', 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('DISTANCE_TO_LTC', 'APPROVED', 'DISTANCE_TO_LTC', 'DISTANCE TO LTC', '', 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('MULTI_STOREY_RATE', 'APPROVED', 'MULTI_STOREY_RATE', 'MULTI-STOREY RATE', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('NO_OF_SETS', 'APPROVED', 'NO_OF_SETS', 'NO. OF SETS', NULL, 'integer', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('RP1cb5fe2e:14cdb1a6034:-78d9', 'APPROVED', 'TOTAL_ADDITIONAL', 'TOTAL_ADDITIONAL', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('RP3153bf8b:1473788097f:-5e15', 'APPROVED', 'NO_OF_UNITS', 'NUMBER OF UNITS', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('RP65bd4b24:147eee7380d:-78b9', 'APPROVED', 'DISTANCE_KM', 'DISTANCE IN KM', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('RP65bd4b24:147eee7380d:5013', 'APPROVED', 'TOTAL_AREA', 'TOTAL AREA', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_ADVANCE', 'APPROVED', 'TOTAL_ADVANCE', 'TOTAL ADVANCE', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_AV', 'APPROVED', 'TOTAL_AV', 'TOTAL AV', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_BMV', 'APPROVED', 'TOTAL_BMV', 'TOTAL BMV', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_CURRENT', 'APPROVED', 'TOTAL_CURRENT', 'TOTAL CURRENT', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_MV', 'APPROVED', 'TOTAL_MV', 'TOTAL MV', '', 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_PREVIOUS', 'APPROVED', 'TOTAL_PREVIOUS', 'TOTAL PREVIOUS', NULL, 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_PRIOR', 'APPROVED', 'TOTAL_PRIOR', 'TOTAL PRIOR', '', 'decimal', '0', '0');
INSERT INTO `rptparameter` (`objid`, `state`, `name`, `caption`, `description`, `paramtype`, `minvalue`, `maxvalue`) VALUES ('TOTAL_VALUE', 'APPROVED', 'TOTAL_VALUE', 'TOTAL VALUE', '', 'decimal', '0', '0');


/* PLANT/TREE */
DELETE FROM planttree;
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fdc', 'APPROVED', 'ABAC', 'ABACA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7dca', 'APPROVED', 'ACAC', 'ACACIA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e7e', 'APPROVED', 'AFRI', 'AFRICAN TULIP');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e87', 'APPROVED', 'AGOH', 'AGOHO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ee1', 'APPROVED', 'ALMO', 'ALMON');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7da6', 'APPROVED', 'AMUG', 'AMUGUIS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ecf', 'APPROVED', 'ANIB', 'ANIBUANG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e00', 'APPROVED', 'ANTI', 'ANTIPOLO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-66ae', 'APPROVED', 'ATIS', 'ATIS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-66e4', 'APPROVED', 'AVOC', 'AVOCADO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fd3', 'APPROVED', 'BAGR', 'BAGRASS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7eea', 'APPROVED', 'BAGT', 'BAGTIKAN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7df7', 'APPROVED', 'BAKA', 'BAKAN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fca', 'APPROVED', 'BAMB', 'BAMBOO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fc1', 'APPROVED', 'BAEX', 'BANANA EXPORT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fb8', 'APPROVED', 'BALO', 'BANANA LOCAL');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7d79', 'APPROVED', 'BANG', 'BANGKAL');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e75', 'APPROVED', 'BANO', 'BANOYO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e09', 'APPROVED', 'BENG', 'BENGUET PINES');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ec6', 'APPROVED', 'BINU', 'BINUANG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7d82', 'APPROVED', 'BOGO', 'BOGO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7faf', 'APPROVED', 'BRUS', 'BRUSH LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7fa4', 'APPROVED', 'CACA', 'CACAO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f9b', 'APPROVED', 'CALA', 'CALAMANSI');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e6c', 'APPROVED', 'CALI', 'CALIANDRA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f92', 'APPROVED', 'CATT', 'CATTLE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-66d2', 'APPROVED', 'CHIC', 'CHICO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-53a6d50d:14c34ba226f:-20bd', 'APPROVED', 'CITR', 'CITRUS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f89', 'APPROVED', 'COCO', 'COCONUT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f80', 'APPROVED', 'COFF', 'COFFEE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f77', 'APPROVED', 'COGO', 'COGON');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e63', 'APPROVED', 'COLO', 'COLO/BREADFRUIT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f6e', 'APPROVED', 'CORN', 'CORN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT2bd5d118:147f4103d2c:-3d92', 'APPROVED', 'DAO', 'DAO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e99', 'APPROVED', 'DITA', 'DITA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-6699', 'APPROVED', 'DUHA', 'DUHAT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f65', 'APPROVED', 'DURI', 'DURIAN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e5a', 'APPROVED', 'DURIN', 'DURIAN NATIVE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7dc1', 'APPROVED', 'EBAG', 'E. BAGRAS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7db8', 'APPROVED', 'ECAM', 'E. CAMALDONES');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f5c', 'APPROVED', 'FALC', 'FALCATA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e51', 'APPROVED', 'FIRE', 'FIRE TREE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f53', 'APPROVED', 'FISH', 'FISHPOND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f4a', 'APPROVED', 'FISI', 'FISHPOND INLAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f31', 'APPROVED', 'FLOW', 'FLOWER LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f28', 'APPROVED', 'FORE', 'FOREST LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f1f', 'APPROVED', 'GEME', 'GEMELINA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-6709', 'APPROVED', 'GUAV', 'GUAVA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e12', 'APPROVED', 'GUBA', 'GUBAS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-66c0', 'APPROVED', 'GUYA', 'GUYABANO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e90', 'APPROVED', 'HIMB', 'HIMBABAO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7eb4', 'APPROVED', 'ILAN', 'ILANG-ILANG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f16', 'APPROVED', 'IPIL', 'IPIL-IPIL');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7f1a', 'APPROVED', 'IPILP', 'IPIL-PREMIUM SPP');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-2cb2e946:147f4943e9a:-77fc', 'APPROVED', 'JACK', 'JACKFRUIT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ebd', 'APPROVED', 'KALU', 'KALUMPANG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7f11', 'APPROVED', 'KAMG', 'KAMAGONG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e24', 'APPROVED', 'KAMA', 'KAMANSI');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7eab', 'APPROVED', 'KAPO', 'KAPOK (DOLDOL)');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ddc', 'APPROVED', 'LANI', 'LANIPAO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7d9d', 'APPROVED', 'LANU', 'LANUTA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f0d', 'APPROVED', 'LANZ', 'LANZONES');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e48', 'APPROVED', 'LAUR', 'LAUAN RED');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e3f', 'APPROVED', 'LAUW', 'LAUAN WHITE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7dee', 'APPROVED', 'LUKT', 'LUKTOB');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5dc36edc:147eb035ac1:-7508', 'APPROVED', 'MABO', 'MABOLO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-53a6d50d:14c34ba226f:-f8f', 'APPROVED', 'MACO', 'MACOPA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7f04', 'APPROVED', 'MAHO', 'MAHOGANY');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ea2', 'APPROVED', 'MALA', 'MALAPAPAYA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e36', 'APPROVED', 'MALU', 'MALUGAY');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7daf', 'APPROVED', 'MANM', 'MANGIUM');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7efb', 'APPROVED', 'MANG', 'MANGO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ef2', 'APPROVED', 'MATN', 'MANGOSTEEN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ee9', 'APPROVED', 'MROV', 'MANGROOVE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ee0', 'APPROVED', 'MARA', 'MARANG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ed7', 'APPROVED', 'MARS', 'MARSH');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT2bd5d118:147f4103d2c:-44cd', 'APPROVED', 'MOLA', 'MOLAVE - PREMIUM SPP');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7f08', 'APPROVED', 'NARR', 'NARRA-PREMIUM SPP');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ece', 'APPROVED', 'NIPA', 'NIPA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-68f1', 'APPROVED', 'NIPD', 'NIPA (CLUMP)');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ec5', 'APPROVED', 'ORCH', 'ORCHARD');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT2bd5d118:147f4103d2c:-3b4a', 'APPROVED', 'OTFR', 'OTHER FRUIT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7d8b', 'APPROVED', 'PAGA', 'PAGATPAT');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7ebc', 'APPROVED', 'PALM', 'PALM OIL');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7eb3', 'APPROVED', 'PAPA', 'PAPAYA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT5a11dd55:14c064d62f1:-68df', 'APPROVED', 'PAPD', 'PAPAYA (PLANT)');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7eaa', 'APPROVED', 'PAST', 'PASTURE LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e9e', 'APPROVED', 'PINE', 'PINEAPPLE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e95', 'APPROVED', 'POME', 'POMELO');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e8c', 'APPROVED', 'RAMB', 'RAMBUTAN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e83', 'APPROVED', 'RAMI', 'RAMIE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e2d', 'APPROVED', 'RIAN', 'RIAN TREE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e7a', 'APPROVED', 'RIWI', 'RICE WITH IRRIGATION');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e71', 'APPROVED', 'RIWO', 'RICE WITHOUT IRRIGATION');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e68', 'APPROVED', 'ROOT', 'ROOTCROPS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e5f', 'APPROVED', 'RUBB', 'RUBBER');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-2cb2e946:147f4943e9a:-785a', 'APPROVED', 'SANT', 'SANTOL');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e56', 'APPROVED', 'SORG', 'SORGHUM');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e4d', 'APPROVED', 'SOYB', 'SOYBEANS');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-2cb2e946:147f4943e9a:-77ee', 'APPROVED', 'STAR', 'STAR APPLE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e44', 'APPROVED', 'SWAM', 'SWAMPLAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e3b', 'APPROVED', 'SWIN', 'SWINE LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7dd3', 'APPROVED', 'TALI', 'TALISAY');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7eff', 'APPROVED', 'TANG', 'TANGUILE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7ed8', 'APPROVED', 'TEAK', 'TEAK-PREMIUM SPP');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7e1b', 'APPROVED', 'THAI', 'THAILAND ACACIA');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e32', 'APPROVED', 'TIMB', 'TIMBER LAND');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e29', 'APPROVED', 'TREE', 'TREE FARM');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7de5', 'APPROVED', 'TUOG', 'TUOG');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-7ceaf220:147d821beaa:-7d94', 'APPROVED', 'ULAY', 'ULAYAN');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-2cb2e946:147f4943e9a:-77e0', 'APPROVED', 'UPLA', 'UPLAND RICE');
INSERT INTO `planttree` (`objid`, `state`, `code`, `name`) VALUES ('PT-40c36a84:147d7147e85:-7e20', 'APPROVED', 'VEGE', 'VEGETABLE TRACK');
